<?php
// load_official_questions.php
require_once 'config.php';

try {
    // Clear existing questions for the 5 tests to avoid duplicates
    $pdo->exec("DELETE FROM ss_questions WHERE test_type IN ('MBTI', 'DISC', 'Big Five', 'PDA', 'Grit Scale')");
    echo "Limpando questões antigas...<br>";

    $questions = [
        // MBTI - 60 Questions
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Prefiro resolver problemas conversando com outras pessoas.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Sinto-me energizado ao estar em grupos.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Tendo a falar mais do que ouvir.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Gosto de estar em ambientes sociais.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Prefiro atividades em grupo do que sozinho.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Fico entediado com tarefas solitárias.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Gosto de iniciar conversas.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Tomo decisões rapidamente em grupo.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Tenho facilidade em me expressar verbalmente.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Gosto de trabalhar em ambientes dinâmicos.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Sinto-me confortável em ambientes com muitas pessoas.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Gosto de compartilhar ideias com colegas.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Prefiro reuniões presenciais às mensagens.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Aprendo melhor com discussões do que com leituras solitárias.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'E/I', 'text' => 'Aprecio ser o centro das atenções.', 'inv' => 0],
        
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Confio mais em fatos do que em intuições.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Prefiro instruções detalhadas às sugestões vagas.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Sou prático e realista.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Dou atenção aos detalhes do presente.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Gosto de seguir processos já conhecidos.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Fico mais confortável com o que é familiar.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Tomo decisões com base em dados concretos.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Gosto de planejar com base no que já aconteceu.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Prefiro ferramentas que já conheço bem.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Sinto segurança em procedimentos formais.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Tenho atenção às etapas operacionais.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Foco no agora mais do que no futuro.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Prefiro métodos tradicionais aos experimentais.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Gosto de resolver problemas com passos definidos.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'S/N', 'text' => 'Valorizo a experiência prática.', 'inv' => 0],

        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Sou objetivo ao lidar com conflitos.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Tomo decisões com base em lógica, não em sentimentos.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Mantenho a razão em situações difíceis.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Gosto de analisar as causas antes de agir.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Não deixo emoções interferirem no trabalho.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Dou feedbacks diretos, mesmo que duros.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Priorizo resultados mais que relacionamentos.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Gosto de argumentar com lógica.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Prefiro dados à empatia.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Evito me envolver emocionalmente em decisões.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Tento manter imparcialidade sempre.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Costumo manter distanciamento emocional em reuniões.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Trabalho bem com métricas e indicadores.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Sou mais racional do que sensível.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'T/F', 'text' => 'Critérios objetivos são mais importantes que opiniões pessoais.', 'inv' => 0],

        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Gosto de seguir cronogramas e prazos.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Prefiro trabalhar com planejamento definido.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Sinto desconforto com mudanças inesperadas.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Sou pontual e organizado.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Tenho listas de tarefas e as sigo.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Planejo meu dia antes de começar.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Tomo decisões rapidamente.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Cumpro rotinas com disciplina.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Gosto de resolver pendências imediatamente.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Evito improvisos no ambiente profissional.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Prefiro ambientes previsíveis.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Gosto de metas claras e definidas.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Fico ansioso com desorganização.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Aprecio quando tudo segue conforme o plano.', 'inv' => 0],
        ['type' => 'MBTI', 'dim' => 'J/P', 'text' => 'Gosto de terminar antes do prazo.', 'inv' => 0],

        // DISC - 28 Questions
        ['type' => 'DISC', 'dim' => 'D', 'text' => 'Gosto de assumir o controle em situações difíceis.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'D', 'text' => 'Sou direto ao expressar minhas opiniões.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'D', 'text' => 'Prefiro tomar decisões rapidamente.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'D', 'text' => 'Tenho facilidade em liderar pessoas.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'D', 'text' => 'Sou motivado por desafios.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'D', 'text' => 'Gosto de competir e vencer.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'D', 'text' => 'Sinto-me confortável em assumir riscos.', 'inv' => 0],

        ['type' => 'DISC', 'dim' => 'I', 'text' => 'Tenho facilidade em convencer as pessoas com minhas ideias.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'I', 'text' => 'Sou comunicativo e extrovertido.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'I', 'text' => 'Gosto de motivar e inspirar os outros.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'I', 'text' => 'Tenho um bom senso de humor e gosto de interagir.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'I', 'text' => 'Aprecio o reconhecimento público.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'I', 'text' => 'Gosto de estar no centro das atenções.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'I', 'text' => 'Sou otimista por natureza.', 'inv' => 0],

        ['type' => 'DISC', 'dim' => 'S', 'text' => 'Prefiro ambientes tranquilos e previsíveis.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'S', 'text' => 'Tenho paciência com os outros.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'S', 'text' => 'Evito mudanças bruscas.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'S', 'text' => 'Sou constante e confiável em minhas ações.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'S', 'text' => 'Gosto de apoiar meus colegas.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'S', 'text' => 'Evito conflitos sempre que possível.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'S', 'text' => 'Sou leal e dedicado à equipe.', 'inv' => 0],

        ['type' => 'DISC', 'dim' => 'C', 'text' => 'Sigo regras e procedimentos com atenção aos detalhes.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'C', 'text' => 'Preocupo-me com a precisão do meu trabalho.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'C', 'text' => 'Evito cometer erros.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'C', 'text' => 'Analiso cuidadosamente antes de tomar decisões.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'C', 'text' => 'Valorizo a qualidade mais do que a velocidade.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'C', 'text' => 'Prefiro ter instruções claras antes de agir.', 'inv' => 0],
        ['type' => 'DISC', 'dim' => 'C', 'text' => 'Sou organizado e meticuloso.', 'inv' => 0],

        // BIG FIVE
        ['type' => 'Big Five', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Gosto de ser o centro das atenções em situações sociais.'],
        ['type' => 'Big Five', 'dim' => 'Conscienciosidade', 'inv' => 0, 'text' => 'Sou uma pessoa muito trabalhadora e dedicada.'],
        ['type' => 'Big Five', 'dim' => 'Abertura', 'inv' => 0, 'text' => 'Aprecio arte, música ou literatura com profundidade.'],
        ['type' => 'Big Five', 'dim' => 'Neuroticismo', 'inv' => 1, 'text' => 'Raramente me sinto triste ou deprimido(a).'],
        ['type' => 'Big Five', 'dim' => 'Amabilidade', 'inv' => 0, 'text' => 'Faço as pessoas ao meu redor se sentirem bem-vindas.'],
        ['type' => 'Big Five', 'dim' => 'Extroversão', 'inv' => 1, 'text' => 'Prefiro ficar em casa a sair e conhecer pessoas novas.'],
        ['type' => 'Big Five', 'dim' => 'Conscienciosidade', 'inv' => 0, 'text' => 'Mantenho meu espaço de trabalho sempre organizado.'],
        ['type' => 'Big Five', 'dim' => 'Abertura', 'inv' => 0, 'text' => 'Tenho curiosidade por culturas e tradições diferentes.'],
        ['type' => 'Big Five', 'dim' => 'Neuroticismo', 'inv' => 0, 'text' => 'Fico irritado(a) com facilidade quando as coisas não saem como planejado.'],
        ['type' => 'Big Five', 'dim' => 'Amabilidade', 'inv' => 0, 'text' => 'Raramente critico os outros pelas suas escolhas.'],
        ['type' => 'Big Five', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Tomo iniciativa em atividades de grupo.'],
        ['type' => 'Big Five', 'dim' => 'Conscienciosidade', 'inv' => 1, 'text' => 'Deixo tarefas pela metade com frequência.'],
        ['type' => 'Big Five', 'dim' => 'Abertura', 'inv' => 0, 'text' => 'Tenho uma imaginação fértil e gosto de fantasiar.'],
        ['type' => 'Big Five', 'dim' => 'Neuroticismo', 'inv' => 1, 'text' => 'Lido bem com críticas sem me sentir abalado(a).'],
        ['type' => 'Big Five', 'dim' => 'Amabilidade', 'inv' => 0, 'text' => 'Ofereço ajuda espontaneamente sem esperar ser solicitado(a).'],
        ['type' => 'Big Five', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Sinto-me energizado(a) após interagir com muitas pessoas.'],
        ['type' => 'Big Five', 'dim' => 'Conscienciosidade', 'inv' => 0, 'text' => 'Sigo regras e procedimentos mesmo quando poderia ignorá-los.'],
        ['type' => 'Big Five', 'dim' => 'Abertura', 'inv' => 0, 'text' => 'Gosto de explorar teorias filosóficas ou científicas complexas.'],
        ['type' => 'Big Five', 'dim' => 'Neuroticismo', 'inv' => 0, 'text' => 'Tenho oscilações de humor frequentes.'],
        ['type' => 'Big Five', 'dim' => 'Amabilidade', 'inv' => 0, 'text' => 'Confio nas boas intenções das pessoas.'],
        ['type' => 'Big Five', 'dim' => 'Extroversão', 'inv' => 1, 'text' => 'Me sinto desconfortável sendo o foco das atenções.'],
        ['type' => 'Big Five', 'dim' => 'Conscienciosidade', 'inv' => 0, 'text' => 'Planejo com antecedência antes de iniciar qualquer projeto.'],
        ['type' => 'Big Five', 'dim' => 'Abertura', 'inv' => 0, 'text' => 'Sou aberto(a) a revisar minhas crenças quando confrontado(a) com novos fatos.'],
        ['type' => 'Big Five', 'dim' => 'Neuroticismo', 'inv' => 0, 'text' => 'Costumo sentir um peso emocional mesmo em situações simples.'],
        ['type' => 'Big Five', 'dim' => 'Amabilidade', 'inv' => 0, 'text' => 'Evito confrontos mesmo quando tenho razão.'],
        ['type' => 'Big Five', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Faço amizades com facilidade em ambientes desconhecidos.'],
        ['type' => 'Big Five', 'dim' => 'Conscienciosidade', 'inv' => 1, 'text' => 'Tenho dificuldade em manter rotinas por longos períodos.'],
        ['type' => 'Big Five', 'dim' => 'Abertura', 'inv' => 0, 'text' => 'Gosto de debater ideias inovadoras, mesmo que controversas.'],
        ['type' => 'Big Five', 'dim' => 'Neuroticismo', 'inv' => 1, 'text' => 'Me recupero rapidamente após situações estressantes.'],
        ['type' => 'Big Five', 'dim' => 'Amabilidade', 'inv' => 0, 'text' => 'Me importo genuinamente com o bem-estar das pessoas ao meu redor.'],
        ['type' => 'Big Five', 'dim' => 'Extroversão', 'inv' => 1, 'text' => 'Prefiro ambientes com pouca interação social.'],
        ['type' => 'Big Five', 'dim' => 'Conscienciosidade', 'inv' => 0, 'text' => 'Cumpro compromissos mesmo quando surgem imprevistos.'],
        ['type' => 'Big Five', 'dim' => 'Abertura', 'inv' => 1, 'text' => 'Prefiro respostas práticas e objetivas a reflexões teóricas.'],
        ['type' => 'Big Five', 'dim' => 'Neuroticismo', 'inv' => 0, 'text' => 'Sinto ansiedade mesmo antes de eventos corriqueiros.'],
        ['type' => 'Big Five', 'dim' => 'Amabilidade', 'inv' => 1, 'text' => 'Dificilmente sinto empatia por pessoas que tomaram decisões ruins.'],
        ['type' => 'Big Five', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Animo o grupo quando percebo que a energia está baixa.'],
        ['type' => 'Big Five', 'dim' => 'Conscienciosidade', 'inv' => 0, 'text' => 'Reviso meu trabalho várias vezes antes de considerá-lo concluído.'],
        ['type' => 'Big Five', 'dim' => 'Abertura', 'inv' => 0, 'text' => 'Experimento abordagens incomuns para resolver problemas do cotidiano.'],
        ['type' => 'Big Five', 'dim' => 'Neuroticismo', 'inv' => 0, 'text' => 'Perco o sono com preocupações relacionadas ao trabalho.'],
        ['type' => 'Big Five', 'dim' => 'Amabilidade', 'inv' => 0, 'text' => 'Compartilho crédito com a equipe mesmo quando fui o principal responsável.'],
        ['type' => 'Big Five', 'dim' => 'Extroversão', 'inv' => 1, 'text' => 'Evito tomar a palavra em reuniões grandes.'],
        ['type' => 'Big Five', 'dim' => 'Conscienciosidade', 'inv' => 0, 'text' => 'Estabeleço metas claras e mensuro meu progresso regularmente.'],
        ['type' => 'Big Five', 'dim' => 'Abertura', 'inv' => 0, 'text' => 'Busco entender perspectivas muito diferentes da minha.'],
        ['type' => 'Big Five', 'dim' => 'Neuroticismo', 'inv' => 0, 'text' => 'Sinto que as coisas raramente vão dar certo para mim.'],

        // PDA
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Aceito desafios mesmo quando o resultado é incerto.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Prefiro arriscar e errar a perder uma boa oportunidade.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Sinto-me energizado quando enfrento situações de alta pressão.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Costumo agir com base na minha intuição, mesmo sem todos os dados.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Não me incomoda tomar decisões que impactem outras pessoas.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Vejo os erros como parte natural do processo de aprender e crescer.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Fico entediado quando tudo vai muito bem e sem imprevistos.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Prefiro liderar situações de crise a esperar alguém tomar a frente.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Tenho facilidade em tomar decisões sob pressão e com pouco tempo.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Não hesito em confrontar situações difíceis quando necessário.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Encaro mudanças repentinas como oportunidades, não como ameaças.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Gosto de trabalhar em ambientes competitivos e de alta performance.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Costumo colocar projetos em prática antes de ter tudo planejado.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Não me preocupo excessivamente com os riscos envolvidos nas minhas decisões.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Sinto-me confortável assumindo responsabilidades de grande impacto.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Prefiro metas arrojadas e difíceis a objetivos seguros e previsíveis.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Tenho facilidade em agir mesmo quando não tenho todas as informações.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Costumo questionar o status quo e propor mudanças ousadas.'],
        ['type' => 'PDA', 'dim' => 'Risco', 'inv' => 0, 'text' => 'Sinto prazer em superar limites que outros consideram impossíveis.'],

        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Gosto de estar no centro das atenções em eventos sociais.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Faço amizades com facilidade em ambientes novos.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Prefiro trabalhar em equipe a realizar tarefas individualmente.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Tenho facilidade em iniciar conversas com pessoas que não conheço.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Sinto-me energizado após interagir com muitas pessoas.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Gosto de apresentar ideias e projetos para grupos grandes.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Consigo expressar minhas opiniões com clareza e entusiasmo.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Prefiro resolver conflitos por meio do diálogo direto.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Tenho facilidade em engajar e motivar as pessoas ao meu redor.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Gosto de ambientes dinâmicos com muito contato interpessoal.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Sinto-me bem em posições de liderança e visibilidade.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Tenho facilidade em adaptar minha comunicação a diferentes perfis de pessoas.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Gosto de participar ativamente de reuniões e discussões em grupo.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Costumo ser a pessoa que quebra o gelo em situações sociais.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Tenho facilidade em construir redes de relacionamento profissional.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Prefiro comunicar más notícias pessoalmente a fazê-lo por escrito.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Sinto prazer genuíno em conhecer pessoas com histórias diferentes da minha.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Consigo manter conversas interessantes com qualquer tipo de pessoa.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Gosto de ambientes onde posso colaborar e trocar ideias constantemente.'],
        ['type' => 'PDA', 'dim' => 'Extroversão', 'inv' => 0, 'text' => 'Tenho facilidade em inspirar confiança nas pessoas rapidamente.'],

        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Consigo manter a calma mesmo em situações de grande tensão.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Prefiro concluir uma tarefa por vez antes de iniciar outra.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Tenho facilidade em esperar o momento certo para agir.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Sinto-me confortável em rotinas estáveis e bem definidas.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Não me apresso para tomar decisões importantes sem refletir antes.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Costumo ouvir com atenção até que o outro termine de falar.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Prefiro construir relacionamentos sólidos a longo prazo.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Tenho facilidade em lidar com pessoas que trabalham em ritmo diferente do meu.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Sinto-me bem em funções que exigem constância e dedicação contínua.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Consigo manter the foco em projetos longos sem perder a motivação.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Prefiro ambientes previsíveis a situações de mudança constante.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Tenho facilidade em suportar períodos de incerteza sem me desestabilizar.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Costumo pensar antes de falar, especialmente em situações delicadas.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Sinto-me confortável realizando tarefas repetitivas quando necessário.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Tenho facilidade em manter a serenidade diante de críticas ou pressões.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Prefiro investir tempo em planejar bem antes de executar.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Costumo oferecer suporte emocional às pessoas ao meu redor.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Tenho facilidade em adaptar meu ritmo ao da equipe sem me frustrar.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Sinto-me bem exercendo funções de apoio e suporte a outras pessoas.'],
        ['type' => 'PDA', 'dim' => 'Paciência', 'inv' => 0, 'text' => 'Prefiro evitar conflitos desnecessários, buscando sempre the consenso.'],

        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Tenho o hábito de verificar meu trabalho mais de uma vez antes de entregar.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Sigo procedimentos e protocolos mesmo quando poderia tomar atalhos.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Fico incomodado quando as pessoas não cumprem prazos combinados.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Gosto de ter processos bem definidos para cada tipo de atividade.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Prefiro trabalhar com dados e fatos concretos antes de tomar decisões.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Sinto desconforto quando tenho que entregar algo que não está no meu melhor nível.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Tenho facilidade em organizar informações de forma lógica e estruturada.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Costumo documentar meu trabalho de forma detalhada e cuidadosa.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Prefiro ter clareza total sobre as expectativas antes de iniciar uma tarefa.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Fico atento a detalhes que outros costumam deixar passar.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Tenho dificuldade em me sentir satisfeito com entregas superficiais ou incompletas.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Prefiro ambientes onde as regras e responsabilidades estão bem definidas.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Sinto-me mais seguro quando tenho um plano claro e organizado.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Costumo questionar processos que parecem imprecisos ou mal definidos.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Tenho facilidade em identificar inconsistências em relatórios e dados.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Prefiro fazer algo certo da primeira vez do que ter que corrigir depois.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Sinto-me responsável pela qualidade do trabalho de toda a equipe, não apenas do meu.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Tenho o hábito de criar checklists e listas de verificação para minhas atividades.'],
        ['type' => 'PDA', 'dim' => 'Norma', 'inv' => 0, 'text' => 'Fico desconfortável quando decisões importantes são tomadas sem embasamento adequado.'],

        // GRIT SCALE
        ['type' => 'Grit Scale', 'dim' => 'Resiliência', 'inv' => 0, 'text' => 'Consigo me recuperar rapidamente após sofrer uma grande decepção.'],
        ['type' => 'Grit Scale', 'dim' => 'Resiliência', 'inv' => 0, 'text' => 'Enxergo os fracassos como aprendizados que me tornam mais forte.'],
        ['type' => 'Grit Scale', 'dim' => 'Resiliência', 'inv' => 0, 'text' => 'Não deixo que críticas ou rejeições me impeçam de seguir em frente.'],
        ['type' => 'Grit Scale', 'dim' => 'Resiliência', 'inv' => 0, 'text' => 'Mantenho minha motivação mesmo quando os resultados demoram a aparecer.'],
        ['type' => 'Grit Scale', 'dim' => 'Perseverança', 'inv' => 0, 'text' => 'Costumo manter o mesmo objetivo principal por anos, sem desviar o foco.'],
        ['type' => 'Grit Scale', 'dim' => 'Perseverança', 'inv' => 0, 'text' => 'Não abandono projetos importantes mesmo quando surgem alternativas mais atraentes.'],
        ['type' => 'Grit Scale', 'dim' => 'Perseverança', 'inv' => 0, 'text' => 'Consigo trabalhar de forma consistente em algo por muito tempo, mesmo sem reconhecimento imediato.'],
        ['type' => 'Grit Scale', 'dim' => 'Perseverança', 'inv' => 0, 'text' => 'Prefiro aprofundar minha expertise em uma área a ficar mudando de direção constantemente.'],
        ['type' => 'Grit Scale', 'dim' => 'Garra', 'inv' => 0, 'text' => 'Sou capaz de me esforçar ao máximo mesmo quando ninguém está me observando.'],
        ['type' => 'Grit Scale', 'dim' => 'Garra', 'inv' => 0, 'text' => 'Minha determinação para alcançar minhas metas supera qualquer obstáculo externo.'],
        ['type' => 'Grit Scale', 'dim' => 'Garra', 'inv' => 0, 'text' => 'Tenho uma paixão clara que guia minhas decisões e esforços no longo prazo.'],
        ['type' => 'Grit Scale', 'dim' => 'Garra', 'inv' => 0, 'text' => 'Faço mais do que o esperado quando estou comprometido com algo que acredito.'],
    ];

    $stmt = $pdo->prepare("INSERT INTO ss_questions (test_type, dimension, question_text, is_inverse) VALUES (?, ?, ?, ?)");
    
    foreach ($questions as $q) {
        $stmt->execute([$q['type'], $q['dim'], $q['text'], $q['inv']]);
    }

    echo "✅ " . count($questions) . " questões carregadas com sucesso (MBTI, DISC, Big Five, PDA e Grit Scale)!";
} catch (Exception $e) {
    echo "❌ Erro ao carregar questões: " . $e->getMessage();
}
?>
