<?php
class PdfToText
{
    public static function parse($filename)
    {
        $content = file_get_contents($filename);
        if (!$content)
            return "";

        $text = "";

        // Very basic PDF extraction logic for standard uncompressed text or simple streams
        // This is not a full PDF parser but works for many simple text PDFs.
        // For production on shared hosting without libraries, this is a fallback.
        // It tries to find text streams.

        // If simple regex fails, we might rely on the fact that sometimes PDF text is in () inside BT...ET blocks
        // But many modern PDFs are compressed. 
        // IF the host has `pdftotext` (poppler), use it.

        if (function_exists('shell_exec') && trim(shell_exec('which pdftotext'))) {
            $output = shell_exec("pdftotext -layout " . escapeshellarg($filename) . " -");
            if ($output)
                return $output;
        }

        // Fallback: simple extraction (often fails on compressed streams)
        // A robust solution without Composer/libraries on shared host is impossible for ALL PDFs.
        // We will try a slightly better pure PHP class if I can write one, but for now let's try the shell_exec or a simple regex.

        // Remove valid PDF structure to likely get text if not compressed
        $result = '';
        if (preg_match_all('/<<[^>]*>>|stream(.*?)endstream/s', $content, $objects)) {
            foreach ($objects[0] as $object) {
                if (strpos($object, 'stream') !== false) {
                    $stream = substr($object, strpos($object, 'stream') + 6, -9);
                    // Try to uncompress
                    $text_chunk = @gzuncompress($stream);
                    if ($text_chunk === false)
                        $text_chunk = $stream; // maybe not compressed
                    $result .= $text_chunk;
                }
            }
        }

        // Clean up result
        // This is a "best effort" without libraries. 
        // For the sake of this task, we will assume standard text extract or shell availability.
        // If it fails, the AI will just see garbage and we can warn the user.

        // Actually, there is a better single file solution: https://github.com/smalot/pdfparser (too big)
        // Let's rely on a vendor folder or valid user assumption.
        // I will write a basic text cleaner that often works on uncompressed PDFs or rely on the user copying text if this fails?
        // No, user wants PDF upload.

        // Let's assume pdftotext might be available or use a basic regex that catches text in parenthesis
        // Many LinkedIn PDFs generated by "Save to PDF" are often readable.

        // A simple text extraction attempt:
        $raw_text = $result ?: $content;
        // Extract text between ()
        preg_match_all('/\((.*?)\)/', $raw_text, $matches);
        $extracted = implode(' ', $matches[1]);

        // If we got very little text, maybe it was not helpful.
        if (strlen($extracted) < 50 && function_exists('shell_exec')) {
            // Try one more time with simple cat/strings if linux
            $strings = shell_exec("strings " . escapeshellarg($filename));
            if ($strings)
                return $strings;
        }

        return $extracted ?: "Não foi possível extrair texto automaticamente deste PDF. O PDF pode ser uma imagem ou estar comprimido.";
    }
}
?>